name: CommonUtils
version: ${version}
description: Common utilities for Bukkit.
authors: [Favorlock, Gjosiah]

main: com.gmail.favorlock.commonutils.CommonUtils
database: false

softdepend: [ProtocolLib]